name: Shortify My URL - Chrome Extension

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get package.json content
      id: get_packageJson
      run: |
        content=`cat ./package.json`
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=packageJson::$content"

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies, Build package
      run: |
        npm ci
        npm run build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{fromJson(steps.get_packageJson.outputs.packageJson).name}}-${{fromJson(steps.get_packageJson.outputs.packageJson).version}}
        path: |
          dist
